### ISSUE TITLE
Reuse already checked out `mdn/content` repo

### ISSUE THREAD

**Issue by OnkarRuikar** [jc-verse/mdn-graph#2]
The current setup requires fresh `mdn/content` checkout in this repo folder. But I already have `mdn/content` checked out and the full build done.

An [.env file with `CONTENT_ROOT` variable](https://github.com/mdn/yari/blob/0cc49fc1121a99a6d262b36d8a789817e6be074e/.env-dist#L1) can be used to point to existing `mdn/content` location. And in the code ([here](https://github.com/jc-verse/mdn-graph/blob/64538b3fd1e872f4ea6de6ef69b26839ec242667/src/server/fix-self-link.ts#L34) and [here](https://github.com/jc-verse/mdn-graph/blob/64538b3fd1e872f4ea6de6ef69b26839ec242667/src/server/create-graph.ts#L79)) [refer to the variable](https://bun.sh/guides/runtime/set-env). The default value of the variable in the file would be `./content`.

While setting up this project, I hardcoded the `mdn/content` path in above mentioned locations and it worked.

**Comment by Josh-Cena** [comment]
The default would be `../content`. For me, I have both `mdn-graph` and `content` under the `mdn` folder. I've added the `CONTENT_ROOT` env var and added `.env` to the gitignores. Bun loads `.env` by default so you should be able to try this.
